Repository DIT112-V21/group-14, pull requests merged in 2021-04, with the labels that each got.

#11 Basic obstacle avoidance
  arduino/smartcar/smartcar.ino
Labels: feature

#14 GUI
  front_end/Scripts.js
  front_end/Settings.html
  front_end/Style/Style.css
  front_end/connect-to-car.html
  front_end/img/back-button.PNG
  front_end/img/backup-camera.PNG
  front_end/img/darkness_mcCroc.png
  front_end/img/xbox-controller.png
  front_end/index.html
  front_end/main.js
  front_end/mainMenu.html
  front_end/package-lock.json
  front_end/package.json
  front_end/preload.js
Labels: GUI, feature

#27 Minor tweaks to Arduino CI and new Electron CI
  .github/workflows/app-build.yml
  .github/workflows/arduino-build.yml
Labels: GUI

#26 Update Darkmode + Music
  front_end/Settings-dark.html
  front_end/Settings.html
  front_end/Style/Darkmode.css
  front_end/Style/Lightmode.css
  front_end/connect-to-car-dark.html
  front_end/connect-to-car.html
  front_end/fonts/DoctorGlitch.otf
  front_end/index.html
  front_end/mainMenu-dark.html
  front_end/mainMenu.html
  front_end/music.js
  front_end/musicSettings.js
  front_end/onLoad.js
  front_end/styleToggling.js
Labels: GUI, enhancement

#29 Improve loginscreen
  front_end/Settings.html
  front_end/Style/Darkmode.css
  front_end/Style/Lightmode.css
  front_end/connect-to-car.html
  front_end/easter-egg.html
  front_end/index.html
  front_end/music.js
  front_end/styleToggling.js
Labels: GUI, bug, enhancement

#30 Connect front and back end + camera
  arduino/smartcar/smartcar.ino
  front_end/Scripts.js
  front_end/connect-to-car.html
  front_end/main.js
Labels: feature

#32 Add gearshifting functionality
  front_end/Scripts.js
  front_end/package-lock.json
Labels: feature

#39 Update to SmartCar
  arduino/smartcar/smartcar.ino
Labels: enhancement
