Repository DIT112-V21/group-14, pull requests merged in 2021-05, with the labels that each got.

#43 Implement camera
  arduino/smartcar/smartcar.ino
  front_end/Scripts.js
  front_end/connect-to-car.html
Labels: GUI, feature

#44 Volume slider
  front_end/Settings.html
  front_end/Style/Darkmode.css
  front_end/Style/Lightmode.css
  front_end/index.html
  front_end/music.js
  front_end/styleToggling.js
Labels: GUI, feature

#45 Revise Darkmode with Class-switching
  front_end/Settings.html
  front_end/Style/Darkmode.css
  front_end/Style/Lightmode.css
  front_end/Style/fonts/CIND.otf
  front_end/Style/fonts/novamono.ttf
  front_end/connect-to-car.html
  front_end/fonts/DoctorGlitch.otf
  front_end/index.html
  front_end/mainMenu.html
  front_end/onLoad.js
  front_end/styleToggling.js
Labels: enhancement, sprint 3

#46 Implement Cruise Control functionality
  front_end/Scripts.js
Labels: enhancement, feature

#49 Optimize CSS and HTML
  front_end/Settings.html
  front_end/Style/Lightmode.css
  front_end/connect-to-car.html
  front_end/index.html
  front_end/mainMenu.html
Labels: GUI, enhancement

#56 Machine learning added to client application
  front_end/Style/Lightmode.css
  front_end/main.js
  machine-learning/models/research/object_detection/mqtt_to_video.py
  machine-learning/models/research/object_detection/requirements.txt
  machine-learning/models/research/object_detection/utils/__pycache__/__init__.cpython-37.pyc
  machine-learning/models/research/object_detection/utils/__pycache__/label_map_util.cpython-37.pyc
  machine-learning/models/research/object_detection/utils/__pycache__/visualization_utils.cpython-37.pyc
Labels: AI, feature

#58 Add popups
  front_end/Scripts.js
  front_end/Style/Lightmode.css
  front_end/connect-to-car.html
  front_end/img/question-mark.png
Labels: GUI, enhancement

#60 Implement ai view
  front_end/Scripts.js
  front_end/Style/Lightmode.css
  front_end/change.js
  front_end/connect-to-car.html
  machine-learning/models/research/object_detection/mqtt_to_video.py
Labels: AI

#61 Credits page
  front_end/Credits.html
  front_end/Style/Lightmode.css
  front_end/mainMenu.html
Labels: GUI

#62 Refactor the code
  front_end/Credits.html
  front_end/Scripts.js
  front_end/Settings.html
  front_end/change.js
  front_end/connect-to-car.html
  front_end/easter-egg.html
  front_end/index.html
  front_end/main.js
  front_end/mainMenu.html
  front_end/onLoad.js
  front_end/preload.js
  front_end/scripts/control-and-camera.js
  front_end/scripts/music.js
  front_end/scripts/onLoad.js
  front_end/scripts/styleToggling.js
  front_end/style/styles.css
  front_end/styleToggling.js
Labels: enhancement

#63 Automated testing
  .github/workflows/app-build.yml
  front_end/main.js
  front_end/package-lock.json
  front_end/package.json
  front_end/test/test.js
Labels: enhancement

#67 Update README
  README.md
Labels: documentation

#68 Add Videolink
  README.md
Labels: documentation
